# Generated by Django 4.0.3 on 2022-03-07 10:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=100)),
                ('sharif', models.CharField(max_length=100)),
                ('jins', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=100)),
                ('tsana', models.DateField()),
                ('tuman', models.CharField(choices=[('davlatobod', 'Davlatobod tumani'), ('namangan_sh', 'Namangan shahri'), ('namangan_t', 'Namangan tumani'), ('norin', 'Norin tumani'), ('mingbuloq', 'Mingbuloq tumani'), ('yangiqoʻrgʻon', 'Yangiqoʻrgʻon tumani'), ('kosonsoy', 'Kosonsoy tumani'), ('pop', 'Pop tumani'), ('toʻraqoʻrgʻon', 'Toʻraqoʻrgʻon tumani'), ('uychi', 'Uychi tumani'), ('uchqoʻrgʻon', 'Uchqoʻrgʻon tumani'), ('chortoq', 'Chortoq tumani'), ('chust', 'Chust tumani')], max_length=100)),
                ('manzil', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('passport', models.CharField(max_length=15)),
                ('rasm', models.ImageField(upload_to='passport_rasmi/%Y/%m/%d/')),
                ('pass_time', models.DateField()),
                ('anketa', models.FileField(upload_to='anketa/%Y/%m/%d/')),
                ('taqdimot_pdf', models.FileField(upload_to='taqdimot_pdf/%Y/%m/%d/')),
                ('loyiha_nomi', models.CharField(max_length=150)),
                ('faloliyat_turi', models.CharField(choices=[('i_ch', 'ishlab chiqarish'), ('savdo', 'savdo'), ('xizmat_k', "hizmat ko'rsatish"), ('boshqa', 'boshqa')], max_length=100)),
                ('st_mazmun', models.CharField(max_length=250)),
                ('st_ahamiyat', models.CharField(max_length=250)),
                ('st_dolzarb', models.CharField(max_length=250)),
                ('yangi_ishchi', models.CharField(max_length=100)),
                ('mijozlar', models.CharField(max_length=250)),
                ('raqobatchilar', models.CharField(choices=[('ha', 'Ha'), ('yoq', "Yo'q")], max_length=100)),
                ('mablag', models.CharField(max_length=100)),
                ('st_natija', models.CharField(max_length=300)),
                ('malumot', models.TextField(blank=True, null=True)),
                ('natija', models.CharField(choices=[('ha', 'Qabul qilindi'), ('yoq', 'Qabul qilinmadi')], default='yoq', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
