# Generated by Django 4.0.3 on 2022-03-07 10:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='iib',
            field=models.CharField(default=1, max_length=250, verbose_name='Passport berilgan IIB'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='anketa',
            field=models.FileField(upload_to='anketa/%Y/%m/%d/', verbose_name='Anketani yuklang'),
        ),
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='info',
            name='faloliyat_turi',
            field=models.CharField(choices=[('i_ch', 'ishlab chiqarish'), ('savdo', 'savdo'), ('xizmat_k', "hizmat ko'rsatish"), ('boshqa', 'boshqa')], max_length=100, verbose_name='Faoliyat turi'),
        ),
        migrations.AlterField(
            model_name='info',
            name='familya',
            field=models.CharField(max_length=100, verbose_name='Familya'),
        ),
        migrations.AlterField(
            model_name='info',
            name='ism',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='info',
            name='jins',
            field=models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=100, verbose_name='Jins'),
        ),
        migrations.AlterField(
            model_name='info',
            name='loyiha_nomi',
            field=models.CharField(max_length=150, verbose_name='Loyiha nomi'),
        ),
        migrations.AlterField(
            model_name='info',
            name='mablag',
            field=models.CharField(max_length=100, verbose_name='Mablag'),
        ),
        migrations.AlterField(
            model_name='info',
            name='malumot',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'shimcha malumot"),
        ),
        migrations.AlterField(
            model_name='info',
            name='manzil',
            field=models.CharField(max_length=250, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='info',
            name='mijozlar',
            field=models.CharField(max_length=250, verbose_name='Mijozlar'),
        ),
        migrations.AlterField(
            model_name='info',
            name='natija',
            field=models.CharField(choices=[('ha', 'Qabul qilindi'), ('yoq', 'Qabul qilinmadi')], default='yoq', max_length=100, verbose_name='Start upning yakuniy natijasi'),
        ),
        migrations.AlterField(
            model_name='info',
            name='pass_time',
            field=models.DateField(verbose_name='Passport berilgan sana'),
        ),
        migrations.AlterField(
            model_name='info',
            name='passport',
            field=models.CharField(max_length=15, verbose_name='Passport seria raqami'),
        ),
        migrations.AlterField(
            model_name='info',
            name='raqobatchilar',
            field=models.CharField(choices=[('ha', 'Ha'), ('yoq', "Yo'q")], max_length=100, verbose_name='Raqobatchilar'),
        ),
        migrations.AlterField(
            model_name='info',
            name='rasm',
            field=models.ImageField(upload_to='passport_rasmi/%Y/%m/%d/', verbose_name='Passport rasmi'),
        ),
        migrations.AlterField(
            model_name='info',
            name='sharif',
            field=models.CharField(max_length=100, verbose_name='Sharif'),
        ),
        migrations.AlterField(
            model_name='info',
            name='st_ahamiyat',
            field=models.CharField(max_length=250, verbose_name='Start up ahamiyati'),
        ),
        migrations.AlterField(
            model_name='info',
            name='st_dolzarb',
            field=models.CharField(max_length=250, verbose_name='Start up dolzarbligi'),
        ),
        migrations.AlterField(
            model_name='info',
            name='st_mazmun',
            field=models.CharField(max_length=250, verbose_name='Start up mazmuni'),
        ),
        migrations.AlterField(
            model_name='info',
            name='st_natija',
            field=models.CharField(max_length=300, verbose_name='Start updan kozlangan  natija'),
        ),
        migrations.AlterField(
            model_name='info',
            name='taqdimot_pdf',
            field=models.FileField(upload_to='taqdimot_pdf/%Y/%m/%d/', verbose_name='Taaqdimotni yuklang'),
        ),
        migrations.AlterField(
            model_name='info',
            name='telefon',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='info',
            name='tsana',
            field=models.DateField(verbose_name="Tug'ilgan sana"),
        ),
        migrations.AlterField(
            model_name='info',
            name='tuman',
            field=models.CharField(choices=[('davlatobod', 'Davlatobod tumani'), ('namangan_sh', 'Namangan shahri'), ('namangan_t', 'Namangan tumani'), ('norin', 'Norin tumani'), ('mingbuloq', 'Mingbuloq tumani'), ('yangiqoʻrgʻon', 'Yangiqoʻrgʻon tumani'), ('kosonsoy', 'Kosonsoy tumani'), ('pop', 'Pop tumani'), ('toʻraqoʻrgʻon', 'Toʻraqoʻrgʻon tumani'), ('uychi', 'Uychi tumani'), ('uchqoʻrgʻon', 'Uchqoʻrgʻon tumani'), ('chortoq', 'Chortoq tumani'), ('chust', 'Chust tumani')], max_length=100, verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='info',
            name='yangi_ishchi',
            field=models.CharField(max_length=100, verbose_name='Yangi ishchi'),
        ),
    ]
